# Gradle Settings
org.gradle.jvmargs=-Xmx2G -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
# Ghost Reference Index
ghostRefIndex=D:/GitHub/MarkusBordihn/Ghost-Reference-Index/gradle/ghost-ref-hytale.gradle
# Project
version=2.4.0
group=de.markusbordihn.cats
vendor_name=markusbordihn
# Mod
mod_id=cats
mod_name=Cats
mod_author=Markus Bordihn
# Hytale Configuration
hytale_build=2026.02.19-1a311a592
hytaleHome=G:/Hytale/install/release
patchline=package/game/latest
hytaleServerJar=G:/Hytale/install/release/package/game/latest/Server/HytaleServer.jar
