/**
 * Hytale Model Exporter (v2)
 *
 * Підтримує як новий формат {pos: [x,y,z], color: "#RRGGBB"}
 * так і legacy формат [[z,y,x]].
 */

export function exportToHytaleJson(voxels) {
    if (!voxels || voxels.length === 0) {
        return JSON.stringify({ error: "No voxel data to export" }, null, 2);
    }

    /** Sanitize color for Hytale style (no pure black/white) */
    const sanitize = (hex) => {
        if (!hex) return "#1E293B";
        const h = hex.toUpperCase();
        if (h === "#000000" || h === "#000") return "#1A1A1A";
        if (h === "#FFFFFF" || h === "#FFF") return "#F0F0F0";
        return h;
    };

    const model = {
        format_version: "2.0",
        type: "hytale_model_generator_export",
        timestamp: new Date().toISOString(),
        description: "Generated by Hytale Model Generator (AI) — RGBA 64³ GAN",
        texture_width: 64,
        texture_height: 64,
        elements: [],
    };

    voxels.forEach((voxel, index) => {
        let x, y, z, color;

        // New format: {pos: [x,y,z], color: "#RRGGBB"}
        if (voxel && typeof voxel === "object" && voxel.pos) {
            [x, y, z] = voxel.pos;
            color = sanitize(voxel.color);
        } else {
            // Legacy: [z, y, x]
            [z, y, x] = voxel;
            color = "#10B981";
        }

        model.elements.push({
            name: `voxel_${index}`,
            from: [x, y, z],
            to: [x + 1, y + 1, z + 1],
            color: color,
            faces: {
                north: { uv: [0, 0, 1, 1], texture: "#0", tint: color },
                east:  { uv: [0, 0, 1, 1], texture: "#0", tint: color },
                south: { uv: [0, 0, 1, 1], texture: "#0", tint: color },
                west:  { uv: [0, 0, 1, 1], texture: "#0", tint: color },
                up:    { uv: [0, 0, 1, 1], texture: "#0", tint: color },
                down:  { uv: [0, 0, 1, 1], texture: "#0", tint: color },
            },
        });
    });

    return JSON.stringify(model, null, 2);
}
