/**
 * Hytale Model Exporter
 * 
 * Converts a list of voxel coordinates into a Hytale Model Format JSON.
 * Since Hytale's official format is complex (bones, animations), we will output a format
 * compatible with Hytale Model Creator (HMC) or a simplified schema that represents the volume.
 * 
 * Current Schema Strategy: List of cuboids.
 */

export function exportToHytaleJson(voxels) {
    // voxels is an array of [z, y, x]

    if (!voxels || voxels.length === 0) {
        return JSON.stringify({ error: "No voxel data to export" }, null, 2);
    }

    // 1. Basic Metadata
    const model = {
        format_version: "1.0",
        type: "hytale_model_generator_export",
        timestamp: new Date().toISOString(),
        description: "Generated by Hytale Model Generator (AI)",
        texture_width: 32, // Simplified assumptions
        texture_height: 32,
        elements: []
    };

    // 2. Convert Voxels to Cuboids
    // For V1, we simply map each voxel to a 1x1x1 cube.
    // Optimization (Greedy Meshing) is a future improvement.

    voxels.forEach((voxel, index) => {
        const [z, y, x] = voxel;

        model.elements.push({
            name: `voxel_${index}`,
            from: [x, y, z],
            to: [x + 1, y + 1, z + 1],
            color: "#10b981", // Default emerald green
            // In a real scenario, we'd map UVs here if we had textures
            faces: {
                north: { uv: [0, 0, 1, 1], texture: "#0" },
                east: { uv: [0, 0, 1, 1], texture: "#0" },
                south: { uv: [0, 0, 1, 1], texture: "#0" },
                west: { uv: [0, 0, 1, 1], texture: "#0" },
                up: { uv: [0, 0, 1, 1], texture: "#0" },
                down: { uv: [0, 0, 1, 1], texture: "#0" }
            }
        });
    });

    return JSON.stringify(model, null, 2);
}
